LICENSE_KEY = "[TRIAL]_this_{AG_Grid}_Enterprise_key_{AG-062754}_is_granted_for_evaluation_only___Use_in_production_is_not_permitted___Please_report_misuse_to_legal@ag-grid.com___For_help_with_purchasing_a_production_key_please_contact_info@ag-grid.com___You_are_granted_a_{Single_Application}_Developer_License_for_one_application_only___All_Front-End_JavaScript_developers_working_on_the_application_would_need_to_be_licensed___This_key_will_deactivate_on_{14 August 2024}____[v3]_[01]_MTcyMzU5MDAwMDAwMA==a5f0bef6477e9746662f8e0f46e475b7"

SAMPLE_DTYPE = {
    "sample_id": "int64",
    "sample_name": "string",
    "patient": "string",
    "sample_type": "string",
    "gender": "string",
    "hospital": "string",
    "department": "string",
    "age": "string",
    "age_float": "float64",
    "age_group": "string",
    "hospital_num": "string",
    "hosp_sampled": "string",
    "doctor": "string",
    "collect_time": "datetime64[ns]",
    "clinical_diagnosis": "string",
    "receive_time": "datetime64[ns]",
    "receive_trial_name": "string",
    "bednumber": "string",
    "number_of_detected_pathos": "Int64",
    "number_of_detected_drugresis": "Int64",
    "出具结果": "string",
}

SAMPLE_COLUMNS = [
    "sample_name",
    "sample_type",
    "gender",
    "age",
    "age_float",
    "age_group",
    "hospital",
    "department",
    "collect_time",
    "receive_time",
    "number_of_detected_pathos",
    "number_of_detected_drugresis",
    "出具结果",
    "clinical_diagnosis",
]
